---
auto: true
server: true
markdown: maruku
cities:
- atlanta: Atlanta, GA
- baltimore: Baltimore, MD
- birmingham: Birmingham, AL
- boston: Boston, MA
- buffalo: Buffalo, NY
- chicago: Chicago, IL
- columbia: Columbia, SC
- columbus: Columbus, OH
- fortwayne: Fort Wayne, IN
- green_bay: Green Bay, WI
- iowa_city: Iowa City, IA
- jersey_city: Jersey City, NJ
- new_york: New York City, NY
- pittsburgh: Pittsburgh, PA
- providence: Providence, RI
- taipei: Taipei, Taiwan
- toronto: Toronto, ON
- windsor: Windsor, ON
