---
markdown: kramdown
cities:
- albuquerque:
    name: Albuquerque, NM
    latitude: 35.110703
    longitude: -106.609991
- alma:
    name: Alma & Saguenay, QC
    latitude: 48.55
    longitude: -71.65
- atlanta:
    name: Atlanta, GA
    latitude: 33.7489954
    longitude: -84.3879824
- austin:
    name: Austin, TX
    latitude: 30.267153
    longitude: -97.7430608
- baltimore:
    name: Baltimore, MD
    latitude: 39.281633
    longitude: -76.5811712
- bangalore:
    name: Bangalore, India
    latitude: 12.9715987
    longitude: 77.5945627
- beijing:
    name: Beijing, China
    latitude: 39.90403
    longitude: 116.407526
- bend:
    name: Bend, OR
    latitude: 44.053125
    longitude: -121.318132
- berlin:
    name: Berlin, Germany
    latitude: 52.519171
    longitude: 13.4060912
- birmingham:
    name: Birmingham, AL
    latitude: 33.5206608
    longitude: -86.80248999999999
- boise:
    name: Boise, ID
    latitude: 43.589235
    longitude: -116.256917
- boston:
    name: Boston, MA
    latitude: 42.3584308
    longitude: -71.0597732
- bristol:
    name: Bristol, UK
    latitude: 51.4522387
    longitude: -2.5900163
- brussels:
    name: Brussels, Belgium
    latitude: 50.8503396
    longitude: 4.3517103
- buffalo:
    name: Buffalo, NY
    latitude: 42.88644679999999
    longitude: -78.8783689
- calgary:
    name: Calgary, AB
    latitude: 51.0419341
    longitude: -114.0360957
- chicago:
    name: Chicago, IL
    latitude: 41.8781136
    longitude: -87.6297982
- cincinnati:
    name: Cincinnati, OH
    latitude: 39.102945
    longitude: -84.508684
- cleveland:
    name: Cleveland, OH
    latitude: 41.510845
    longitude: -81.567016
- columbia:
    name: Columbia, SC
    latitude: 34.0007104
    longitude: -81.0348144
- columbus:
    name: Columbus, OH
    latitude: 39.9611755
    longitude: -82.99879419999999
- dallas:
    name: Dallas, TX
    latitude: 32.842833
    longitude: -96.771825
- dayton:
    name: Dayton, OH
    latitude: 39.7589478
    longitude: -84.1916069
- denton:
    name: Denton, TX
    latitude: 33.215349
    longitude: -97.13459499999999
- dublin:
    name: Dublin, Ireland
    latitude: 53.3399637
    longitude: -6.259983099999999
- east_lansing:
    name: East Lansing, MI
    latitude: 42.7255116
    longitude: -84.4667982
- eindhoven:
    name: Eindhoven, Netherlands
    latitude: 51.44164199999999
    longitude: 5.4697225
- erie:
    name: Erie, PA
    latitude: 42.12922409999999
    longitude: -80.085059
- fortwayne:
    name: Fort Wayne, IN
    latitude: 41.079273
    longitude: -85.1393513
- frederick:
    name: Frederick, MD
    latitude: 39.4140561
    longitude: -77.40889179999999
- green_bay:
    name: Green Bay, WI
    latitude: 44.51915899999999
    longitude: -88.019826
- haverhill:
    name: Haverhill, MA
    latitude: 42.7754552
    longitude: -71.085962
- honolulu:
    name: Honolulu, HI
    latitude: 21.3069444
    longitude: -157.8583333
- houghton:
    name: Houghton, MI
    latitude: 47.12113309999999
    longitude: -88.5694182
- iowa_city:
    name: Iowa City, IA
    latitude: 41.6611277
    longitude: -91.5301683
- istanbul:
    name: Istanbul,Turkey
    latitude: 41.00527
    longitude: 28.97696
- ithaca:
    name: Ithaca, NY
    latitude: 42.4388483
    longitude: -76.4989697
- izmir:
    name: Izmir, Turkey
    latitude: 38.418881
    longitude: 27.128671
- kharkov:
    name: Kharkov, Ukraine
    latitude: 49.9935
    longitude: 36.230383
- kyiv:
    name: Kyiv, Ukraine
    latitude: 50.4501
    longitude: 30.5234
- liege:
    name: Liege, Belgium
    latitude: 50.6325574
    longitude: 5.5796662
- lisbon:
    name: Lisbon, Portugal
    latitude: 38.7222524
    longitude: -9.1393366
- logan:
    name: Logan, UT
    latitude: 41.7369803
    longitude: -111.8338359
- london:
    name: London, UK
    latitude: 51.5170986
    longitude: -0.1460838
- los_angeles:
    name: Los Angeles, CA
    latitude: 34.0522342
    longitude: -118.2436849
- louisville:
    name: Louisville, KY
    latitude: 38.253777
    longitude: -85.74844399999999
- manchester:
    name: Manchester, NH
    latitude: 42.99663109999999
    longitude: -71.4670062
- manchester_ct:
    name: Manchester, CT
    latitude: 41.769803
    longitude: -72.520349
- melbourne:
    name: Melbourne, Australia
    latitude: -37.814107
    longitude: 144.96328
- miami:
    name: Miami, FL
    latitude: 25.7889689
    longitude: -80.2264393
- munich:
    name: Munich, Germany
    latitude: 48.1430014
    longitude: 11.5399758
- naperville:
    name: Naperville, IL
    latitude: 41.7858629
    longitude: -88.1472893
- naples:
    name: Naples, FL
    latitude: 26.1420358
    longitude: -81.7948103
- new_york:
    name: New York City, NY
    latitude: 40.7143528
    longitude: -74.00597309999999
- newcastle_upon_tyne:
    name: Newcastle upon Tyne, UK
    latitude: 54.969488
    longitude: -1.618375
- odessa:
    name: Odessa, Ukraine
    latitude: 46.484583
    longitude: 30.7326
- philadelphia:
    name: Philadelphia, PA
    latitude: 39.952335
    longitude: -75.16378900000001
- phoenix:
    name: Phoenix, AZ
    latitude: 33.4483771
    longitude: -112.0740373
- pittsburgh:
    name: Pittsburgh, PA
    latitude: 40.44062479999999
    longitude: -79.9958864
- portland:
    name: Portland, OR
    latitude: 45.5230622
    longitude: -122.6764816
- porto_alegre:
    name: Porto Alegre, Brazil
    latitude: -30.0277041
    longitude: -51.2287346
- providence:
    name: Providence, RI
    latitude: 41.8239891
    longitude: -71.4128343
- quebec:
    name: Quebec, QC
    latitude: 46.8170671
    longitude: -71.2059882
- rochester:
    name: Rochester, NY
    latitude: 43.1621834
    longitude: -77.620859
- rotterdam:
    name: Rotterdam, Nederland
    latitude: 51.9278891
    longitude: 4.3503239
- salem:
    name: Salem, MA
    latitude: 42.5214548
    longitude: -70.8975349
- san_antonio:
    name: San Antonio, TX
    latitude: 29.4241219
    longitude: -98.49362819999999
- san_francisco:
    name: San Francisco, CA
    latitude: 37.7749295
    longitude: -122.4194155
- santa_barbara:
    name: Santa Barbara, CA
    latitude: 34.431903
    longitude: -119.848416
- savannah:
    name: Savannah, GA
    latitude: 32.0835407
    longitude: -81.09983419999999
- shanghai:
    name: Shanghai, China
    latitude: 31.203405
    longitude: 121.481323
- st_catharines:
    name: St. Catharines, ON
    latitude: 39.71819929999999
    longitude: -104.9510427
- st_helier:
    name: St. Helier, Jersey
    latitude: 49.1868225
    longitude: -2.1065682
- sydney:
    name: Sydney, Australia
    latitude: -33.8674869
    longitude: 151.2069902
- syracuse:
    name: Syracuse, NY
    latitude: 43.0481221
    longitude: -76.14742439999999
- taipei:
    name: Taipei, Taiwan
    latitude: 25.04684
    longitude: 121.51737
- tallahassee:
    name: Tallahassee, FL
    latitude: 30.43429
    longitude: -84.28942699999999
- toledo:
    name: Toledo, OH
    latitude: 41.6639
    longitude: -83.5553
- toronto:
    name: Toronto, ON
    latitude: 43.653226
    longitude: -79.3831843
- tulsa:
    name: Tulsa, OK
    latitude: 36.1539
    longitude: -95.9925
- valencia:
    name: Valencia, Spain
    latitude: 39.4708924
    longitude: -0.3675956
- vancouver:
    name: Vancouver, BC
    latitude: 49.261226
    longitude: -123.1139268
- victoria:
    name: Victoria, BC
    latitude: 48.425648
    longitude: -123.3648836
- washington:
    name: Washington, DC
    latitude: 38.93246000000001
    longitude: -77.2379629
- waterloo:
    name: Waterloo, ON
    latitude: 43.4642578
    longitude: -80.5204096
- windsor:
    name: Windsor, ON
    latitude: 42.3183446
    longitude: -83.0342423
- ybor_city:
    name: Ybor City, FL
    latitude: 27.9650212
    longitude: -82.4350941
